# - platform: icloud3
#   username: !secret icloud_username
#   password: !secret icloud_password
#   tracking_method: famshr
#   track_devices:
#   - iPhone > maxence.png
#   - iphone_de_melanie > melanie.png

- platform: synology_srm
  host: 192.168.1.32
  username: !secret srm_username
  password: !secret srm_password