sensor:
  - platform: radarr_upcoming_media
    api_key: !secret radarr_secret
    host: !secret radarr_host
    port: 443
    days: 14
    ssl: true
    theaters: false
    max: 10
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_secret
    host: !secret sonarr_host
    port: 443
    days: 14
    ssl: true
    max: 10